@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [FilmController]
  [FilmResolver]
  [FilmFileController]

  [FilmService]
  [FilmFileService]

  [Film]

}


cloud {
    [Mongoose]
}

cloud {
    [MongoDB\nNative Driver]
}


database "acme (MongoDB)" {
    [Collection Film]
    [GridFS]
}


RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [FilmController]
[RequestLoggerMiddleware] ~~> [FilmResolver]
[RequestLoggerMiddleware] ~~> [FilmFileController]

[FilmController] --> [FilmService]
[FilmResolver] --> [FilmService]
[FilmFileController] --> [FilmFileService]
[FilmService] ..> [Film]

[Film] ~~> [Mongoose]
[FilmFileService] ~~> [MongoDB\nNative Driver]
[Mongoose] ~~> [Collection Film]
[MongoDB\nNative Driver] ~~> [GridFS]

footer (c) Jürgen Zimmermann

@enduml
