@startuml Use Cases

actor Gast
actor Admin
actor Kunde

rectangle kunde {
    Gast --> (Film suchen)
    Admin --> (Film suchen)
    Admin --> (Film anlegen)
    Admin --> (Flm ändern)
    Admin --> (Film löschen)
    Admin --> (Datei hochladen)
    Admin --> (Datei herunterladen)
    Kunde --> (Film suchen)
    Kunde --> (Film anlegen)
    Kunde --> (Film ändern)
    Kunde --> (Datei herunterladen)
}

footer (c) Jürgen Zimmermann

@enduml
