/ Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -   V e r b i n d u n g   n o t w e n d i g
//

### Einloggen in der Rolle "admin", "mitarbeiter" und "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "p") { token expiresIn roles }
}

### Einloggen in der Rolle "mitarbeiter" und "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "alfred.alpha", password: "p") { token expiresIn roles }
}

### Einloggen in der Rolle "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "dirk.delta", password: "p") { token expiresIn roles }
}

### Einloggen mit falschem Passwort
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "FALSCH") { token expiresIn roles }
}

### Neuer Film anlegen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    titel: "Testmutation",
    rating: 1,
    genre: ACTION,
    studio: DISNEY,
    online: true,
    datum: "2021-01-31",
    homepage: "http://acme.com",
    schlagwoerter: ["SPANNEND"]
  )
}

### Neuer Film mit ungueltigen Daten anlegen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    titel: "?!$",
    rating: 999,
    genre: ROMANCE,
    studio: DISNEY,
    online: true,
    datum: "123",
    homepage: "?!$",
    schlagwoerter: ["LIEBE"]
  )
}

### Vorhandener Film aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    id: "000000000000000000000003",
    version: 0,
    film: {
      titel: "Geaendertgraphql",
      rating: 5,
      genre: ACTION,
      studio: DISNEY,
      online: false,
      datum: "2021-01-02",
      homepage: "https://acme.graphql",
      schlagwoerter: [
        "GRUSELIG",
        "SPANNEND"
      ]
    }
  )
}

### Vorhandener Film mit ungueltigen Werten aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    id: "000000000000000000000003",
    version: 0,
    film: {
      titel: "?!$",
      rating: 999,
      genre: ACTION,
      studio: DISNEY,
      online: false,
      datum: "123",
      homepage: "?!$",
      schlagwoerter: ["SPANNEND"]
    }
  )
}

### Nicht-Vorhandener Film aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    id: "999999999999999999999999",
    version: 0,
    film: {
      titel: "Nichtvorhanden",
      rating: 5,
      genre: COMEDY,
      studio: DISNEY,
      online: false,
      datum: "2021-01-02",
      homepage: "https://acme.com",
      schlagwoerter: [
        "SPANNEND",
        "LIEBE"
      ]
    }
  )
}

### Vorhandener Film loeschen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  delete(id: "000000000000000000000004")
}
